/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Main_Package;

import static Main_Package.Html_Window.TagsCode;
import static Main_Package.Html_Window.Update;
import java.awt.Color;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.Highlighter;

/**
 *
 * @author Trevor
 */
public class Main_Window extends javax.swing.JFrame { 
    static DefaultListModel DLM = new DefaultListModel();
    static Html_Window HtmlWindow = new Html_Window();
    static Css_Window CssWindow = new Css_Window();
    static  FileWriter Writer ;
    static Console_Window ConsoleWindow = new Console_Window();
    
   

    /**
     * Creates new form Main_Window
     */
   
    public Main_Window() {
         initComponents();
        Main_Window.super.setIconImage((Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Main_Package/JWeb.png"))));
        if(DLM.isEmpty() == true){
        DLM.addElement("Html Main");
        DLM.addElement("Html Doctype");
        DLM.addElement("Html Center");
        DLM.addElement("Html Body");
        DLM.addElement("Html Head");
        DLM.addElement("Html Title");
        DLM.addElement("Html Img"); 
        DLM.addElement("Html Pargraph");
        DLM.addElement("Html Header 1");
        DLM.addElement("Html Header 2");
        DLM.addElement("Html Header 3");
        DLM.addElement("Html Header 4");
        DLM.addElement("Html Header 5");
        DLM.addElement("Html Header 6");
        DLM.addElement("Html Line Break");
        DLM.addElement("Html Style Link");
        DLM.addElement("Html Link");
        DLM.addElement("Html Meta Char");
        DLM.addElement("Html Meta Keywords");
        DLM.addElement("Html Meta Description");
        DLM.addElement("Html Quotes");
        DLM.addElement("Html Italicize Text");
        DLM.addElement("Html Bold Text");
        DLM.addElement("Html Small Text");
        DLM.addElement("Html Subscripts");
        DLM.addElement("Html Superscripts");
        
       
       }else{
            
            
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        TestPopUp = new javax.swing.JPopupMenu();
        jScrollPane2 = new javax.swing.JScrollPane();
        TagList = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        HtmlMain = new javax.swing.JButton();
        HtmlHeader = new javax.swing.JButton();
        HtmlVoid = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        GetTag = new javax.swing.JButton();
        HtmlVideo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ErrorText = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        ErrorButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        Html_Textarea = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        Css_Textarea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Save = new javax.swing.JMenuItem();
        Load = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        WebsiteGen = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        ImgLoader = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        Windows = new javax.swing.JMenuItem();
        Nimbus = new javax.swing.JMenuItem();
        Metal = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        Console = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenu8.setText("jMenu8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JWeb IDE 1.0");

        TagList.setModel(DLM);
        TagList.setToolTipText("Html and Css Tags");
        jScrollPane2.setViewportView(TagList);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/6.png"))); // NOI18N
        jButton1.setToolTipText("Shows only the Html Tags");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/Css3.png"))); // NOI18N
        jButton2.setToolTipText("Shows only the Css tags");
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/JavaWindow.png"))); // NOI18N
        jButton3.setToolTipText("Shows all tags");
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        HtmlMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/Html File.png"))); // NOI18N
        HtmlMain.setToolTipText("Shows only most Common used Tags");
        HtmlMain.setContentAreaFilled(false);

        HtmlHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/HtmlFile1.png"))); // NOI18N
        HtmlHeader.setToolTipText("Shows tags like the Header Tags");
        HtmlHeader.setContentAreaFilled(false);

        HtmlVoid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/4.png"))); // NOI18N
        HtmlVoid.setToolTipText("Shows the Void Html Tags");
        HtmlVoid.setContentAreaFilled(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/HtmlIcon.png"))); // NOI18N
        jLabel1.setText("  Choose Tag");

        GetTag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/3.png"))); // NOI18N
        GetTag.setToolTipText("Open Html or Css Tags Editer based of what the user Selected");
        GetTag.setContentAreaFilled(false);
        GetTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetTagActionPerformed(evt);
            }
        });

        HtmlVideo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/9.png"))); // NOI18N
        HtmlVideo.setToolTipText("Video and Sound Tags for Html");
        HtmlVideo.setContentAreaFilled(false);

        jLabel2.setText("Tag Orders");

        ErrorText.setColumns(20);
        ErrorText.setLineWrap(true);
        ErrorText.setRows(5);
        ErrorText.setWrapStyleWord(true);
        jScrollPane3.setViewportView(ErrorText);

        jLabel3.setText("Html Code Errors");

        ErrorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/Cut.png"))); // NOI18N
        ErrorButton.setToolTipText("Checks for Errors ");
        ErrorButton.setContentAreaFilled(false);
        ErrorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ErrorButtonActionPerformed(evt);
            }
        });

        Html_Textarea.setColumns(20);
        Html_Textarea.setLineWrap(true);
        Html_Textarea.setRows(5);
        Html_Textarea.setWrapStyleWord(true);
        Html_Textarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Html_TextareaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Html_TextareaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Html_TextareaMousePressed(evt);
            }
        });
        Html_Textarea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Html_TextareaKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(Html_Textarea);

        jTabbedPane1.addTab("Html", jScrollPane4);

        Css_Textarea.setColumns(20);
        Css_Textarea.setLineWrap(true);
        Css_Textarea.setRows(5);
        Css_Textarea.setWrapStyleWord(true);
        jScrollPane5.setViewportView(Css_Textarea);

        jTabbedPane1.addTab("Css", jScrollPane5);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/HtmlIcon.png"))); // NOI18N

        jMenuBar1.setBorderPainted(false);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/Html File.png"))); // NOI18N
        jMenu1.setText("File");

        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/SaveFile.png"))); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jMenu1.add(Save);

        Load.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/NewWindow.png"))); // NOI18N
        Load.setText("Load");
        Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadActionPerformed(evt);
            }
        });
        jMenu1.add(Load);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/2.png"))); // NOI18N
        jMenuItem9.setText("Import Html File or Css File");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/1.png"))); // NOI18N
        jMenuItem10.setText("Export Html File and Css File");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/4.png"))); // NOI18N
        jMenuItem4.setText("Load Html Tag");
        jMenu1.add(jMenuItem4);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/ExitButton.png"))); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu1.add(Exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/Edit.png"))); // NOI18N
        jMenu2.setText("Edit");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/8.png"))); // NOI18N
        jMenuItem3.setText("Edit Html tag");
        jMenu2.add(jMenuItem3);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/3.png"))); // NOI18N
        jMenuItem12.setText("Edit Css tag");
        jMenu2.add(jMenuItem12);

        jMenuBar1.add(jMenu2);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/About.png"))); // NOI18N
        jMenu7.setText("About");

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/JWebIcon.png"))); // NOI18N
        jMenuItem18.setText("JWeb");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem18);

        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/10.png"))); // NOI18N
        jMenuItem19.setText("Console");
        jMenu7.add(jMenuItem19);

        jMenuBar1.add(jMenu7);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/HtmlIcon.png"))); // NOI18N
        jMenu3.setText("Html");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/HtmlFile1.png"))); // NOI18N
        jMenuItem1.setText("New Tag");
        jMenu3.add(jMenuItem1);

        WebsiteGen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/Help.png"))); // NOI18N
        WebsiteGen.setText("Options");
        jMenu3.add(WebsiteGen);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/New Html.png"))); // NOI18N
        jMenuItem5.setText("Website Generator");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        ImgLoader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/2.png"))); // NOI18N
        ImgLoader.setText("Img Loader");
        jMenu3.add(ImgLoader);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/Css3.png"))); // NOI18N
        jMenu4.setText("Css");

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/Css.png"))); // NOI18N
        jMenuItem11.setText("New Css tag");
        jMenu4.add(jMenuItem11);

        jMenuItem8.setText("Options");
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/View.png"))); // NOI18N
        jMenu5.setText("View");

        Windows.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/Windows.png"))); // NOI18N
        Windows.setText("Windows");
        Windows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WindowsActionPerformed(evt);
            }
        });
        jMenu5.add(Windows);

        Nimbus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/JavaWindow.png"))); // NOI18N
        Nimbus.setText("Nimbus");
        Nimbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NimbusActionPerformed(evt);
            }
        });
        jMenu5.add(Nimbus);

        Metal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/Window.png"))); // NOI18N
        Metal.setText("Metal");
        Metal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MetalActionPerformed(evt);
            }
        });
        jMenu5.add(Metal);

        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/7.png"))); // NOI18N
        jMenuItem20.setText("Color Chooser");
        jMenu5.add(jMenuItem20);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/Console.png"))); // NOI18N
        jMenu6.setText("Developers");

        Console.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/10.png"))); // NOI18N
        Console.setText("Console");
        Console.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsoleActionPerformed(evt);
            }
        });
        jMenu6.add(Console);

        jMenuBar1.add(jMenu6);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/Help.png"))); // NOI18N
        jMenu9.setText("Help");

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/Css3.png"))); // NOI18N
        jMenuItem15.setText("Css");
        jMenu9.add(jMenuItem15);

        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/HtmlIcon.png"))); // NOI18N
        jMenuItem16.setText("Html");
        jMenu9.add(jMenuItem16);

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Package/JWebIcon.png"))); // NOI18N
        jMenuItem17.setText("JWeb");
        jMenu9.add(jMenuItem17);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ErrorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HtmlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HtmlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HtmlVoid, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HtmlVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GetTag, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 21, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GetTag)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(HtmlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HtmlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(HtmlVoid, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(HtmlVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85)
                                .addComponent(ErrorButton)
                                .addGap(11, 11, 11))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GetTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetTagActionPerformed
        // TODO add your handling code here:
       
        String List =(String) TagList.getSelectedValue();
        //int[] ListAll = TagList.getSelectedIndices();
        if(List.length() < 1){
            JOptionPane.showMessageDialog(null,"You Need to Choose a Tag");
            
        }else{
            if(List.contains("Html") ==  true){
                 HtmlWindow.Run(List); 
                
            }else{
                //Run Css Window.
                CssWindow.Run(List);
                
                
            }
         
            
        }
        
       // if(List.contentEquals("Html Main")){
          //  HtmlWindow.TagsCode.setText("<html> \n\n\n\n\n\n\n</html>");
            
       // }
        //if(List.contentEquals("Html Body")){
       // HtmlWindow.TagsCode.setText("<body> \n\n\n\n\n\n\n</body>");
        
        
       // }
    
       
        
    }//GEN-LAST:event_GetTagActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        //About JWeb
        AboutJWeb_Window JWeb =new AboutJWeb_Window();
        JWeb.Run();
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        //Export
         String OutPut = Html_Textarea.getText();
        String OutPutCss = Css_Textarea.getText();
         
         try {
              
              FileChooser Filechooser = new FileChooser();
              Filechooser.jFileChooser1.showSaveDialog(null);
              if(Filechooser.jFileChooser1.getSelectedFile().exists()){
              Filechooser.jFileChooser1.getSelectedFile().delete();
            
             }else{
              Writer = new FileWriter(Filechooser.jFileChooser1.getSelectedFile()+".html");
              Writer.append(OutPut);
              Writer.flush();
              Writer.close();
              Writer = new FileWriter(Filechooser.jFileChooser1.getSelectedFile()+".css");
              Writer.append(OutPutCss);
              Writer.flush();
              Writer.close();
              System.out.println("Done");
             }
         } catch (IOException ex) {
             Logger.getLogger(Main_Window.class.getName()).log(Level.SEVERE, null, ex);
             
         }
         
       
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        //Import
         FileChooser Filechooser = new FileChooser();
              Filechooser.jFileChooser1.showOpenDialog(null);
              System.out.println(Filechooser.jFileChooser1.getSelectedFile() );
               if( Html_Textarea.getText().length() <1){
                     Html_Textarea.setText("");
                 }
               if( Css_Textarea.getText().length() <1){
                     Html_Textarea.setText("");
                 }
              if( Filechooser.jFileChooser1.getSelectedFile().isFile()){
            try {
                
                 BufferedReader Reader = new BufferedReader(new FileReader(Filechooser.jFileChooser1.getSelectedFile()));
                
                String line;
                while((line = Reader.readLine()) !=null){
                    if(Filechooser.jFileChooser1.getSelectedFile().toString().contains(".css")){
                       Css_Textarea.append(line);
                        
                    }else{
                   if(Filechooser.jFileChooser1.getSelectedFile().toString().contains(".html"))
                       System.out.println("In Html: "+ line);
                         Html_Textarea.append(line);
                    }
                 
             }
                Reader.close();
                
               
            } catch (IOException ex) {
                Logger.getLogger(Main_Window.class.getName()).log(Level.SEVERE, null, ex);
                
            }
              }else{
                JOptionPane.showMessageDialog(null, "You Need to Choose a File" );
               
              }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void Html_TextareaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Html_TextareaKeyPressed
        // TODO add your handling code here:
          int KeyCode = evt.getKeyCode();
        if(KeyCode == KeyEvent.VK_ALT){
            Html_Textarea.setText("");
          
            
        }
         if(KeyCode == KeyEvent.VK_F1){
             HtmlQuickAdd_Window Html = new HtmlQuickAdd_Window(); 
             System.out.append("Trying to Print to the Text area ");
         Html.Run();
            
        }
        
        
        if(KeyCode == KeyEvent.VK_CONTROL){
            String text = Html_Textarea.getSelectedText();
           String HtmlEx ="<html></html>";
        String BodyEx = "<body></body>";
        String HeadEx = "<head></head>";
        ErrorText.append(text);
        //Over all Check///Start
        if(Html_Textarea.getText().contains("<html></html>")){
            ErrorText.append("Html WorkSpace has Html Tags! now Checking for body tags");
        }else{
             ErrorText.append("Ever WebSite needs a Html tag to start out with add one with the Html tag editer");
            
        }
        if(Html_Textarea.getText().contains("<body></body>")){
           ErrorText.append("Has Body Tags");
        }else{
            ErrorText.append("All Good Website have a body add one with the tag editer");
            
        }
        if(Html_Textarea.getText().contains("<head></head>")){
           ErrorText.append("Has Body Tags");
        }else{
            ErrorText.append("You need a head add one with the tag editer");
            
        }
        
        
        
        
       if(text.contains(HtmlEx)){
           System.out.println(text);
           ErrorText.append(text);
           
       }
        
          
            
         
          
            
        }
        
    }//GEN-LAST:event_Html_TextareaKeyPressed

    private void WindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WindowsActionPerformed
        // TODO add your handling code here:
        Main_Window.super.dispose();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       new Main_Window().setVisible(true);
         
           
        
    }//GEN-LAST:event_WindowsActionPerformed

    private void NimbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NimbusActionPerformed
        // TODO add your handling code here:
         Main_Window.super.dispose();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       new Main_Window().setVisible(true);
         
           
    }//GEN-LAST:event_NimbusActionPerformed

    private void MetalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MetalActionPerformed
        // TODO add your handling code here:
         Main_Window.super.dispose();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       new Main_Window().setVisible(true);
        
        
    }//GEN-LAST:event_MetalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DLM.removeAllElements();
        DLM.addElement("Css Font");
        DLM.addElement("Css Text size");
        DLM.addElement("Css Color");
        DLM.addElement("Css Backround Img");
        DLM.addElement("Css Backround Color");
        DLM.addElement("Css Backround Box Model");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DLM.removeAllElements();
        DLM.addElement("Html Main");
        DLM.addElement("Html Doctype");
        DLM.addElement("Html Center");
        DLM.addElement("Html Body");
        DLM.addElement("Html Head");
        DLM.addElement("Html Title");
        DLM.addElement("Html Img"); 
        DLM.addElement("Html Pargraph");
        DLM.addElement("Html Header 1");
        DLM.addElement("Html Header 2");
        DLM.addElement("Html Header 3");
        DLM.addElement("Html Header 4");
        DLM.addElement("Html Header 5");
        DLM.addElement("Html Header 6");
        DLM.addElement("Html Line Break");
        DLM.addElement("Html Style Link");
        DLM.addElement("Html Link");
        DLM.addElement("Html Meta Char");
        DLM.addElement("Html Meta Keywords");
        DLM.addElement("Html Meta Description");
        DLM.addElement("Html Quotes");
        DLM.addElement("Html Italicize Text");
        DLM.addElement("Html Bold Text");
        DLM.addElement("Html Small Text");
        DLM.addElement("Html Subscripts");
        DLM.addElement("Html Superscripts");
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DLM.removeAllElements();
        DLM.addElement("Html Main");
        DLM.addElement("Html Doctype");
        DLM.addElement("Html Center");
        DLM.addElement("Html Body");
        DLM.addElement("Html Head");
        DLM.addElement("Html Title");
        DLM.addElement("Html Img"); 
        DLM.addElement("Html Pargraph");
        DLM.addElement("Html Header 1");
        DLM.addElement("Html Header 2");
        DLM.addElement("Html Header 3");
        DLM.addElement("Html Header 4");
        DLM.addElement("Html Header 5");
        DLM.addElement("Html Header 6");
        DLM.addElement("Html Line Break");
        DLM.addElement("Html Style Link");
        DLM.addElement("Html Link");
        DLM.addElement("Html Meta Char");
        DLM.addElement("Html Meta Keywords");
        DLM.addElement("Html Meta Description");
        DLM.addElement("Html Quotes");
        DLM.addElement("Html Italicize Text");
        DLM.addElement("Html Bold Text");
        DLM.addElement("Html Small Text");
        DLM.addElement("Html Subscripts");
        DLM.addElement("Html Superscripts");
        DLM.addElement("Css Font");
        DLM.addElement("Css Text size");
        DLM.addElement("Css Color");
        DLM.addElement("Css Backround Img");
        DLM.addElement("Css Backround Color");
        DLM.addElement("Css Backround Box Model");
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Html_TextareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Html_TextareaMouseClicked
        // TODO add your handling code here:
     
       
        
        
    }//GEN-LAST:event_Html_TextareaMouseClicked

    private void ConsoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsoleActionPerformed
        // TODO add your handling code here:
        ConsoleWindow.Run();
       
    }//GEN-LAST:event_ConsoleActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_ExitActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
         String OutPut = Html_Textarea.getText();
         String OutPutCss = Css_Textarea.getText();
         try {
              
              FileChooser Filechooser = new FileChooser();
              Filechooser.jFileChooser1.showSaveDialog(null);
              if(Filechooser.jFileChooser1.getSelectedFile().exists()){
              Filechooser.jFileChooser1.getSelectedFile().delete();
            
             }else{
              Writer = new FileWriter(Filechooser.jFileChooser1.getSelectedFile()+".JWebProjectHtml");
              Writer.append(OutPut);
              Writer.flush();
              Writer.close();
              Writer = new FileWriter(Filechooser.jFileChooser1.getSelectedFile()+".JWebProjectCss");
              Writer.append(OutPutCss);
              Writer.flush();
              Writer.close();
              System.out.println("Done");
             }
         } catch (IOException ex) {
             Logger.getLogger(Main_Window.class.getName()).log(Level.SEVERE, null, ex);
             
         }
        
        
        
    }//GEN-LAST:event_SaveActionPerformed

    private void LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadActionPerformed
        // TODO add your handling code here:
          Html_Textarea.setText("");
   FileChooser Filechooser = new FileChooser();
              Filechooser.jFileChooser1.showOpenDialog(null);
              System.out.println(Filechooser.jFileChooser1.getSelectedFile() );
              if( Filechooser.jFileChooser1.getSelectedFile().isFile()){
            try {
                
                 BufferedReader Reader = new BufferedReader(new FileReader(Filechooser.jFileChooser1.getSelectedFile()));
                 
                String line;
                while((line = Reader.readLine()) !=null){
                  if(Filechooser.jFileChooser1.getSelectedFile().toString().contains(".JWebProjectCss")){
                       Css_Textarea.append(line);
                        
                    }else{
                   if(Filechooser.jFileChooser1.getSelectedFile().toString().contains(".JWebProjectHtml"))
                       System.out.println("In Html: "+ line);
                         Html_Textarea.append(line);
                    }
             }
                Reader.close();
                
               
            } catch (IOException ex) {
                Logger.getLogger(Main_Window.class.getName()).log(Level.SEVERE, null, ex);
                
            }
              }else{
                JOptionPane.showMessageDialog(null, "You Need to Choose a File" );
               
              }
    }//GEN-LAST:event_LoadActionPerformed

    private void ErrorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ErrorButtonActionPerformed
        // TODO add your handling code here:
        String Text = Html_Textarea.getText();
        String SelText = Html_Textarea.getSelectedText().trim();
        String HtmlEx ="<html></html>";
        String BodyEx = "<body></body>";
        String HeadEx = "<head></head>";
       if(SelText.contains(HtmlEx)){
           System.out.println(SelText);
           
       }
        
    }//GEN-LAST:event_ErrorButtonActionPerformed

    private void Html_TextareaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Html_TextareaMouseEntered
        // TODO add your handling code here:
     //When it enters the textarea
    }//GEN-LAST:event_Html_TextareaMouseEntered

    private void Html_TextareaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Html_TextareaMousePressed
        // TODO add your handling code here:
        if(evt.isAltDown() == true){
            
            
        }else{
            //? Coming soon
            
        }
        
        
    }//GEN-LAST:event_Html_TextareaMousePressed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        WebSiteGen_Window Gen = new WebSiteGen_Window();
        Gen.Run();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    
     public  void SetTextHtml(String Text){
         Html_Textarea.setText(Text);
        
            
            
        }
     public void SetTextCss(String Text){
         Css_Textarea.setText(Text);
         
     }
     public void SetTextHtmlGen(String Text){
       Html_Textarea.setText(Text);
      Html_Textarea.setText(Html_Textarea.getText());
         
     }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Console;
    public static javax.swing.JTextArea Css_Textarea;
    private javax.swing.JButton ErrorButton;
    private javax.swing.JTextArea ErrorText;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JButton GetTag;
    private javax.swing.JButton HtmlHeader;
    private javax.swing.JButton HtmlMain;
    private javax.swing.JButton HtmlVideo;
    private javax.swing.JButton HtmlVoid;
    public static javax.swing.JTextArea Html_Textarea;
    private javax.swing.JMenuItem ImgLoader;
    private javax.swing.JMenuItem Load;
    private javax.swing.JMenuItem Metal;
    private javax.swing.JMenuItem Nimbus;
    private javax.swing.JMenuItem Save;
    public javax.swing.JList TagList;
    private javax.swing.JPopupMenu TestPopUp;
    private javax.swing.JMenuItem WebsiteGen;
    private javax.swing.JMenuItem Windows;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private static javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
